import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3a3939",
        "secondary-container": "#47494c",
        "surface-container-highest": "#353534",
        "primary-fixed": "#ffe087",
        "tertiary-fixed-dim": "#c8c7bc",
        primary: "#ffd341",
        "secondary-fixed-dim": "#c5c6ca",
        surface: "#131313",
        "on-tertiary-container": "#4b4c43",
        "primary-fixed-dim": "#eec224",
        "on-secondary-container": "#b7b8bc",
        secondary: "#c5c6ca",
        "on-surface-variant": "#d1c5ad",
        "surface-variant": "#353534",
        "tertiary-container": "#bdbcb1",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#313030",
        "on-secondary": "#2e3133",
        "on-tertiary-fixed-variant": "#47473f",
        "tertiary-fixed": "#e4e3d8",
        "error-container": "#93000a",
        "on-primary-container": "#5c4900",
        "on-tertiary": "#303129",
        background: "#131313",
        "surface-dim": "#131313",
        "on-error": "#690005",
        "surface-container": "#201f1f",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        outline: "#9a9079",
        "surface-container-lowest": "#0e0e0e",
        tertiary: "#d9d8cd",
        "outline-variant": "#4d4633",
        "on-secondary-fixed": "#191c1e",
        "surface-container-low": "#1c1b1b",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#e2b714",
        "on-primary-fixed-variant": "#574500",
        "on-secondary-fixed-variant": "#45474a",
        "on-primary-fixed": "#231a00",
        "surface-tint": "#eec224",
        "inverse-primary": "#735c00",
        "on-primary": "#3c2f00",
        "on-tertiary-fixed": "#1b1c15",
        error: "#ffb4ab",
        "secondary-fixed": "#e1e2e6",
        "on-background": "#e5e2e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-page": "64px",
        gutter: "24px",
        "container-max": "1100px",
      },
      fontFamily: {
        "code-sm": ["Space Grotesk", "monospace"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "code-sm": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
